Vagrant.configure("2") do |config|
    config.env.enable
  
    config.vm.define "ubuntu-cloud-init"
    config.vm.box = "focal-server-cloudimg-amd64-vagrant"
    config.vm.box_url = "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64-vagrant.box"
  
    config.vm.provider "virtualbox" do |v|
      v.name = "ubuntu-cloud-init"
    end
  
    config.vm.cloud_init do |cloud_init|
      cloud_init.content_type = "text/cloud-config"
      cloud_init.path = "data2.yml"
    end
  end
