---
- name: Install MariaDB
  hosts: ynov
  become: true

  tasks:
  - name: Add MariaDB
    apt:
      name: mariadb-server
      state: present

  - name: Start MariaDB
    service:
      name: mariadb
      state: started
