Vagrant.configure("2") do |config|
  
    # Configuration commune à toutes les machines
    config.vm.box = "generic/ubuntu2004"
    
  
    # Ajoutez cette ligne afin d'accélérer le démarrage de la VM (si une erreur 'vbguest' est levée, voir la note un peu plus bas)
    config.vbguest.auto_update = false
    # Désactive les updates auto qui peuvent ralentir le lancement de la machine
    config.vm.box_check_update = false 
    # La ligne suivante permet de désactiver le montage d'un dossier partagé (ne marche pas tout le temps directement suivant vos OS, versions d'OS, etc.)
    config.vm.synced_folder ".", "/vagrant", disabled: true
  
    config.vm.provider "virtualbox" do |vb|
      vb.gui = true
    end

    # Config une première VM "admin"
    config.vm.define "tp3.ynov" do |tp3|
    end
end
